Metrics/MethodLength:
  Max: 15

Layout/LineLength:
  Max: 100

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150

Metrics/AbcSize:
  Max:  18

# These are testing and routing methods.
Metrics/BlockLength:
  ExcludedMethods:
    - describe
    - context
    - included
    - it
    - define
    - factory
    - trait
    - before
    - after
    - resources
    - member
    - collection
    - scope
    - namespace
    - draw
    - task

Style/BracesAroundHashParameters:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false
